-- 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS restaurant CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE restaurant;

-- 레스토랑 테이블 생성
CREATE TABLE IF NOT EXISTS restaurant_info (
                                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                          management_number VARCHAR(50) UNIQUE,
    id INT,
    service_name VARCHAR(100),
    service_id VARCHAR(100),
    city_code VARCHAR(20),
    management_number varchar(50),
    license_date VARCHAR(20),
    license_cancel_date VARCHAR(20),
    business_status_code VARCHAR(20),
    business_status VARCHAR(50),
    detailed_business_status_code VARCHAR(20),
    detailed_business_status VARCHAR(50),
    closure_date VARCHAR(20),
    suspension_start_date VARCHAR(20),
    suspension_end_date VARCHAR(20),
    reopening_date VARCHAR(20),
    phone_number VARCHAR(50),
    area DOUBLE,
    postal_code VARCHAR(20),
    address VARCHAR(200),
    road_address VARCHAR(200),
    road_postal_code VARCHAR(20),
    business_name VARCHAR(100),
    last_modified_time VARCHAR(30),
    data_update_type VARCHAR(50),
    data_update_date VARCHAR(20),
    business_type VARCHAR(100),
    coordinate_x VARCHAR(50),
    coordinate_y VARCHAR(50),
    sanitary_business_type VARCHAR(100),
    male_employee_count INT,
    female_employee_count INT,
    surrounding_classification VARCHAR(100),
    grade_classification VARCHAR(50),
    water_facility_type VARCHAR(50),
    total_employee_count INT,
    head_office_employee_count INT,
    factory_office_employee_count INT,
    factory_sales_employee_count INT,
    factory_production_employee_count INT,
    building_ownership_type VARCHAR(50),
    deposit_amount DOUBLE,
    monthly_rent DOUBLE,
    multi_use_business_yn VARCHAR(1),
    facility_total_scale DOUBLE,
    traditional_designation_number VARCHAR(50),
    traditional_main_food VARCHAR(100),
    website VARCHAR(200),

    INDEX idx_city_code (city_code),
    INDEX idx_business_status (business_status),
    INDEX idx_business_type (business_type),
    INDEX idx_license_date (license_date),
    INDEX idx_closure_date (closure_date)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;